# PrivateTalk v1.0 configuration file

#   %CONVERSATION% = Name of conversation they are in
#   %PLAYER% = Player's name
#   &MESSAGE% = Player's message
party-message-format: "&d[%CONVERSATION%] &7%PLAYER% ≫ &d%MESSAGE%"

#This is the amount of time in minutes that an user who leaves the server 
#in a party can join back, if this time expires then they are removed from the party!

time-to-join-back: 5

