# Welcome to the PrivateTalk v1.0 configuration file!

# format of party-chat messages
party-chat-format: "&e[%CONVERSATION%] &7%PLAYER% ≽ &e%MESSAGE%"

# time in minutes that offline players in conversations should be removed
time-to-kick: 5