name: PrivateTalk
author: Perotin
version: 1.0
main: me.perotin.privatetalk.PrivateTalk
commands:
   privatetalk:
      usage: /privatetalk
      aliases: [pt]
      description: Base command for PrivateTalk